### PR TITLE
fix _getWordPos

### PR DESCRIPTION
**Pull request by blackmiaool**

### CODE REVIEW

**Comment by ahmadnazir** [comment]
@blackmiaool Thanks for the fix. Can you kindly share an example which the original regexp failed? Thanks.

**Comment by blackmiaool** [comment]
@ahmadnazir 
```
1=2
a=b
```
Put cursor between = and b, then alt+b and cursor moves to 2 (should move to a).
Put cursor between a and =, then alt+f and cursor doesn't (should move to b).

**Comment by ahmadnazir** [comment]
@blackmiaool Thanks for the explanation. Appreciate it!

**Comment by Taariqq** [comment]
Is the fix available already?

**Comment by blackmiaool** [comment]
@Taariqq    It's merged, so it's available.

**Comment by Taariqq** [comment]
Do I get update notification in Brackets or have to download manually. Sorry, not too good at this.
And thank you for responding @blackmiaool

**Comment by ahmadnazir** [comment]
@Taariqq I will create a new release and upload the latest version. Once that is done, I believe that you should get a notification about it.

**Comment by Taariqq** [comment]
@ahmadnazir Great! I Love the extension.

**Comment by ahmadnazir** [comment]
@Taariqq Thanks! The extension has been uploaded. Please let me know if you face any problems.

**Pull request merged**
